language: go
go:
- 1.7
sudo: required
services:
- docker
before_install:
- go get github.com/mattn/goveralls
script:
- "$GOPATH/bin/goveralls -service=travis-ci"
notifications:
    slack: kittentl:moBQCRlnTw615glK6ogAaZ1w