[API]
port = 4000
version = "1.0"
debug = true
endpoint = "localhost"
jwt = "apGmlulxoovY00sse099yV5hMaUHZnP7" # CHANGE ME
secure = false

[DB]
server = "mongo:27017"
database = "timeline"
user = ""
password = ""

[Cache]
server = "redis"
port = 6379
user = ""
password = ""

[UploadImage]
path = "uploads/img/"