version: '2'

services:
  staging:
    restart: always
    build: .
    ports:
      - "443:443"
    command: go run server.go
    volumes:
      - data:/go
      - .:/go/src/github.com/TinyKitten/TimelineServer
    links:
      - redis
      - mongo

  redis:
    restart: always
    image: redis
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes

  mongo:
    restart: always
    image: mongo
    volumes:
      - ./data/mongo:/data/db

volumes:
  data:
    driver: 'local'
